version: '3'

services:

  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
        - redis
    networks:
      - app-network

  redis:
      image: redis:latest
      container_name: redis
      ports:
          - "6379:6379"
      volumes:
          - ./redis-data:/data
      networks:
          - app-network
  db:
      image: postgres:latest
      container_name: postgres
      environment:
          POSTGRES_DB: ${DB_DATABASE}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
          - "5432:5432"
      volumes:
          - ./postgres-data:/var/lib/postgresql/data
      networks:
          - app-network

  adminer:
      image: adminer
      container_name: adminer
      environment:
          ADMINER_DEFAULT_SERVER: db
          ADMINER_DEFAULT_USERNAME: ${DB_USERNAME}
          ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
          ADMINER_DEFAULT_DATABASE: ${DB_DATABASE}
      ports:
          - "8080:8080"
      networks:
          - app-network

networks:
  app-network:
    external:
      name: app-network
